apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  # Use ClusterIP instead of LoadBalancer because we don't need to expose the service to the outside world
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
