apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      # Same ports writed in dockerfile and nginx.conf 
      port: 80
      targetPort: 80