apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata: 
      labels:
        app: tasks
    spec: 
      containers:
        - name: tasks
          image: daniofiore/kub-demo-tasks:latest
          env:
            - name: AUTH_ADDRESS
              # We can directly use the service IP address because it will not change, but it is annoying to find it every time. We can use the kubernetes env variable to get the IP address. The service name is used as a domain to send request to and this is possible only in the same cluster. the name is followed by a dot and a namespace.
              # Namespaces: are used to assign namespace to our service, the default is 'default', so we have to pass the namespace to the value
              # value: "10.102.214.63"
              value: "auth-service.default"
            - name : TASKS_FOLDER
              value: "tasks"
