apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata: 
      labels:
        app: users
    spec: 
      containers:
        - name: users
          image: daniofiore/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: localhost
        - name: auth
          image: daniofiore/kub-demo-auth:latest
