apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: host-pvc
spec:
  volumeName: host-pv # NAME OF OUR PV IN host-pv.yaml
  accessModes:
    - ReadWriteOnce # THE SAME IN host-pv.yaml, if we use multiple pods with multiple accessModes, we can add it
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi # WE CAN REQUEST LESS BUT NOT MORE THAN THE MAX STORAGE INDICATED IN OUR host-pv.yaml

